### ISSUE TITLE
it is not working with obsidian 1.74

### ISSUE THREAD

**Issue by noor-tg** [GavinRigsby/obsidian-embed-and-edit-code#2]
hi, I installed this plugin with BRAT. in obisidian 1.74. but it is not working.
any help ?
thanks

**Comment by GavinRigsby** [comment]
What OS are you using? 
Did you enable Detect all file extensions under Settings > Files & Links?
How are you testing if the plugin is working? 

I tested in 1.77 using BRAT to install and it worked correctly.

**Comment by noor-tg** [comment]
I will check it with 1.77

**Comment by noor-tg** [comment]
> What OS are you using? Did you enable Detect all file extensions under Settings > Files & Links? How are you testing if the plugin is working?

- void linux.
- yes I enabled the setting.

> I tested in 1.77 using BRAT to install and it worked correctly.
I tested now on void linux with obsidian 1.7.7 and brat:
- the editor is working.
- but embed code in md file is not.

**example of embed**:
```embed-ts
` ` ` embed-ts
PATH: "vault://features/search/script.ts"
TITLE: "Simple Search"
` ` `
```
without space between ticks

**Comment by noor-tg** [comment]
but the 2 original plugins work correctly (at least with basic features).

thanks
